#!/bin/bash
set -e

echo "Creating database: $KEYCLOAK_DB for user: $KEYCLOAK_DB_USER"

# 1. Create the Keycloak database and user.
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
	CREATE DATABASE "$KEYCLOAK_DB";
	CREATE USER "$KEYCLOAK_DB_USER" WITH ENCRYPTED PASSWORD '$KEYCLOAK_DB_PASSWORD';
	GRANT ALL PRIVILEGES ON DATABASE "$KEYCLOAK_DB" TO "$KEYCLOAK_DB_USER";
EOSQL

# 2. Grant the Keycloak user DDL and DML privileges within the database.
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$KEYCLOAK_DB" <<-EOSQL
	GRANT ALL ON SCHEMA public TO "$KEYCLOAK_DB_USER";
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "$KEYCLOAK_DB_USER";
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "$KEYCLOAK_DB_USER";
EOSQL
